{{ $roleName := printf "%s-role" .Chart.Name }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels: {{ include "spark-hs-chart.labels" (dict "componentName" $roleName "context" $) | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - services
  verbs:
    - "*"
{{- end }}

{{ $roleBindingName := printf "%s-role-binding" .Chart.Name }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBindingName }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{ include "spark-hs-chart.labels" (dict "componentName" $roleBindingName "context" $) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName }}
subjects:
- name:  {{ include "spark-hs-chart.serviceAccountName" . }}
  kind: ServiceAccount
{{- end }}
